import React, { useState } from 'react';
import { Sparkles, Play, Plus, Sliders, Activity, Disc, Check, Flame } from 'lucide-react';
import { useAudio } from '../context/AudioContext';
import { generateAIPlaylist, getSimilarSongs, parsePromptToAudioFeatures } from '../services/recommendationEngine';
import SongCard from '../components/SongCard';

const PROMPT_PRESETS = [
  "⚡ High-energy synthwave for late night coding",
  "☕ Rainy day lo-fi study beats with warm acoustic vibe",
  "🔥 Pumping EDM & techno for heavy gym workout",
  "🌿 Relaxing ambient meditation for deep focus",
  "🎷 Smooth jazz lounge for evening coffee relaxation"
];

export default function AIDiscovery({ setActiveTab, setSelectedPlaylistId }) {
  const { songs, playTrack, createPlaylist, addSongToPlaylist } = useAudio();
  
  const [prompt, setPrompt] = useState(PROMPT_PRESETS[0]);
  const [tempo, setTempo] = useState(120);
  const [energy, setEnergy] = useState(0.85);
  const [valence, setValence] = useState(0.70);
  const [danceability, setDanceability] = useState(0.80);
  const [acousticness, setAcousticness] = useState(0.10);

  const [generatedTracks, setGeneratedTracks] = useState(() => 
    generateAIPlaylist({ prompt: PROMPT_PRESETS[0], songCatalog: songs, count: 6 })
  );

  const [selectedRadarSong, setSelectedRadarSong] = useState(songs[0]);
  const [savedPlaylistSuccess, setSavedPlaylistSuccess] = useState(false);

  const handleGenerateFromPrompt = (promptText) => {
    const parsed = parsePromptToAudioFeatures(promptText);
    setTempo(parsed.tempo);
    setEnergy(parsed.energy);
    setValence(parsed.valence);
    setDanceability(parsed.danceability);
    setAcousticness(parsed.acousticness);

    const results = generateAIPlaylist({
      prompt: promptText,
      targetFeatures: parsed,
      songCatalog: songs,
      count: 6
    });
    setGeneratedTracks(results);
  };

  const handleGenerateFromSliders = () => {
    const customTarget = { tempo, energy, valence, danceability, acousticness };
    const results = generateAIPlaylist({
      targetFeatures: customTarget,
      songCatalog: songs,
      count: 6
    });
    setGeneratedTracks(results);
  };

  const handleSaveAsPlaylist = () => {
    if (generatedTracks.length === 0) return;
    const plName = `🤖 AI Mix: ${prompt.slice(0, 24)}...`;
    const newPl = createPlaylist(plName, 'Generated by TuneWave AI Music Recommendation Engine', generatedTracks[0]?.coverUrl);
    generatedTracks.forEach(t => addSongToPlaylist(newPl.id, t.id));
    setSavedPlaylistSuccess(true);
    setTimeout(() => setSavedPlaylistSuccess(false), 3000);
  };

  const radarMatches = getSimilarSongs(selectedRadarSong, songs, 5);

  return (
    <div className="page-body animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '2.5rem' }}>
      {/* Header */}
      <div style={{
        padding: '2.5rem',
        borderRadius: 'var(--radius-lg)',
        background: 'linear-gradient(135deg, rgba(29,185,84,0.2) 0%, rgba(168,85,247,0.2) 50%, rgba(6,182,212,0.2) 100%)',
        border: '1px solid rgba(29,185,84,0.3)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between'
      }}>
        <div>
          <div className="badge badge-purple" style={{ marginBottom: '0.5rem' }}>
            INTELLIGENT MUSIC ENGINE
          </div>
          <h1 style={{ fontSize: '2.4rem', fontWeight: 800 }}>TuneWave AI DJ & Playlist Generator</h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '1rem', maxWidth: '650px', marginTop: '0.35rem' }}>
            Generate instant custom playlists tailored to your exact mood, activity, or audio feature vectors using Cosine Similarity calculations.
          </p>
        </div>
        <Sparkles size={64} color="var(--primary)" style={{ opacity: 0.8 }} />
      </div>

      {/* Grid: Prompt Generator & Feature Sliders */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
        {/* Natural Language Prompt Generator */}
        <div className="glass-panel" style={{ padding: '1.75rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
            <Sparkles size={20} color="var(--primary)" />
            <h2 style={{ fontSize: '1.2rem', fontWeight: 800 }}>Prompt-Based AI Playlist</h2>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 700, color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
              DESCRIBE YOUR DESIRED VIBE OR ACTIVITY
            </label>
            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g. Upbeat 80s synthwave for late night coding"
                style={{
                  flex: 1,
                  padding: '0.75rem 1rem',
                  borderRadius: 'var(--radius-md)',
                  background: 'rgba(255,255,255,0.06)',
                  border: '1px solid var(--border-light)',
                  color: 'var(--text-main)',
                  fontSize: '0.9rem',
                  outline: 'none'
                }}
              />
              <button
                onClick={() => handleGenerateFromPrompt(prompt)}
                className="btn-primary"
                style={{ flexShrink: 0 }}
              >
                <span>Generate</span>
              </button>
            </div>
          </div>

          <div>
            <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-subtle)', textTransform: 'uppercase', display: 'block', marginBottom: '0.5rem' }}>
              POPULAR AI PRESET PROMPTS
            </span>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              {PROMPT_PRESETS.map((preset, idx) => (
                <button
                  key={idx}
                  onClick={() => {
                    setPrompt(preset);
                    handleGenerateFromPrompt(preset);
                  }}
                  style={{
                    textAlign: 'left',
                    padding: '0.5rem 0.75rem',
                    borderRadius: 'var(--radius-sm)',
                    background: 'rgba(255,255,255,0.04)',
                    border: '1px solid rgba(255,255,255,0.06)',
                    color: 'var(--text-main)',
                    fontSize: '0.85rem',
                    cursor: 'pointer',
                    transition: 'background 0.15s ease'
                  }}
                >
                  {preset}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Audio Feature Vector Sliders */}
        <div className="glass-panel" style={{ padding: '1.75rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
              <Sliders size={20} color="var(--accent-cyan)" />
              <h2 style={{ fontSize: '1.2rem', fontWeight: 800 }}>Fine-Tune Audio Features</h2>
            </div>
            <button
              onClick={handleGenerateFromSliders}
              className="btn-secondary"
              style={{ padding: '0.35rem 0.85rem', fontSize: '0.8rem' }}
            >
              Apply Sliders
            </button>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.2rem' }}>
                <span>Tempo / Speed</span>
                <span style={{ color: 'var(--accent-cyan)' }}>{tempo} BPM</span>
              </div>
              <input type="range" min="60" max="180" value={tempo} onChange={(e) => setTempo(Number(e.target.value))} />
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.2rem' }}>
                <span>Energy Intensity</span>
                <span style={{ color: 'var(--primary)' }}>{Math.round(energy * 100)}%</span>
              </div>
              <input type="range" min="0" max="1" step="0.05" value={energy} onChange={(e) => setEnergy(Number(e.target.value))} />
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.2rem' }}>
                <span>Valence / Mood Happiness</span>
                <span style={{ color: 'var(--accent-purple)' }}>{Math.round(valence * 100)}%</span>
              </div>
              <input type="range" min="0" max="1" step="0.05" value={valence} onChange={(e) => setValence(Number(e.target.value))} />
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.2rem' }}>
                <span>Danceability</span>
                <span style={{ color: '#f43f5e' }}>{Math.round(danceability * 100)}%</span>
              </div>
              <input type="range" min="0" max="1" step="0.05" value={danceability} onChange={(e) => setDanceability(Number(e.target.value))} />
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.2rem' }}>
                <span>Acousticness</span>
                <span style={{ color: '#f59e0b' }}>{Math.round(acousticness * 100)}%</span>
              </div>
              <input type="range" min="0" max="1" step="0.05" value={acousticness} onChange={(e) => setAcousticness(Number(e.target.value))} />
            </div>
          </div>
        </div>
      </div>

      {/* Generated AI Playlist Results */}
      <section>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.25rem' }}>
          <div>
            <h2 style={{ fontSize: '1.4rem', fontWeight: 800 }}>Generated AI Tracklist</h2>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Top matches evaluated by multi-dimensional feature distance scoring.</p>
          </div>

          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button
              onClick={() => playTrack(generatedTracks[0], generatedTracks)}
              className="btn-primary"
            >
              <Play size={18} fill="#000" />
              <span>Stream AI Mix</span>
            </button>
            <button
              onClick={handleSaveAsPlaylist}
              className="btn-secondary"
            >
              {savedPlaylistSuccess ? <Check size={18} color="var(--primary)" /> : <Plus size={18} />}
              <span>{savedPlaylistSuccess ? 'Saved to Library!' : 'Save to Playlists'}</span>
            </button>
          </div>
        </div>

        <div className="cards-grid">
          {generatedTracks.map(song => (
            <div key={song.id} style={{ position: 'relative' }}>
              <div style={{
                position: 'absolute',
                top: '12px',
                right: '12px',
                zIndex: 10,
                background: 'rgba(9,9,11,0.85)',
                backdropFilter: 'blur(8px)',
                padding: '0.25rem 0.5rem',
                borderRadius: 'var(--radius-full)',
                fontSize: '0.72rem',
                fontWeight: 800,
                color: 'var(--primary)',
                border: '1px solid rgba(29,185,84,0.4)'
              }}>
                {song.matchPercentage}% AI Match
              </div>
              <SongCard song={song} queueContext={generatedTracks} />
            </div>
          ))}
        </div>
      </section>

      {/* Cosine Similarity Track Radar Tool */}
      <section className="glass-panel" style={{ padding: '1.75rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '1rem' }}>
          <Activity size={22} color="var(--primary)" />
          <h2 style={{ fontSize: '1.3rem', fontWeight: 800 }}>Track Vector Similarity Radar</h2>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: '2rem', alignItems: 'start' }}>
          <div>
            <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 700, color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
              CHOOSE A SEED TRACK FOR COSINE MATCHING
            </label>
            <select
              value={selectedRadarSong?.id}
              onChange={(e) => {
                const s = songs.find(x => x.id === e.target.value);
                if (s) setSelectedRadarSong(s);
              }}
              style={{
                width: '100%',
                padding: '0.75rem 1rem',
                borderRadius: 'var(--radius-md)',
                background: 'rgba(255,255,255,0.08)',
                border: '1px solid var(--border-light)',
                color: 'var(--text-main)',
                fontSize: '0.9rem',
                outline: 'none',
                marginBottom: '1rem'
              }}
            >
              {songs.map(s => (
                <option key={s.id} value={s.id} style={{ background: '#18181b', color: '#fff' }}>
                  {s.title} - {s.artist} ({s.genre})
                </option>
              ))}
            </select>

            {selectedRadarSong && (
              <div className="glass-card" style={{ padding: '1rem', display: 'flex', gap: '1rem', alignItems: 'center' }}>
                <img src={selectedRadarSong.coverUrl} alt={selectedRadarSong.title} style={{ width: '60px', height: '60px', borderRadius: '8px', objectFit: 'cover' }} />
                <div>
                  <div style={{ fontWeight: 700, fontSize: '0.95rem' }}>{selectedRadarSong.title}</div>
                  <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{selectedRadarSong.artist}</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--primary)', fontWeight: 600, marginTop: '0.2rem' }}>
                    {selectedRadarSong.genre} • {selectedRadarSong.features?.tempo} BPM
                  </div>
                </div>
              </div>
            )}
          </div>

          <div>
            <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: '0.75rem' }}>
              Closest Audio Profile Matches to "{selectedRadarSong?.title}"
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              {radarMatches.map((item, i) => (
                <div
                  key={item.id}
                  onClick={() => playTrack(item)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '0.65rem 1rem',
                    borderRadius: 'var(--radius-md)',
                    background: 'rgba(255,255,255,0.04)',
                    cursor: 'pointer'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <span style={{ fontWeight: 700, color: 'var(--text-subtle)', width: '15px' }}>{i + 1}</span>
                    <img src={item.coverUrl} alt={item.title} style={{ width: '36px', height: '36px', borderRadius: '4px', objectFit: 'cover' }} />
                    <div>
                      <div style={{ fontWeight: 700, fontSize: '0.88rem' }}>{item.title}</div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{item.artist}</div>
                    </div>
                  </div>
                  <div className="badge badge-cyan">
                    {item.matchPercentage}% Cosine Similarity
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
